---

- name: Test NAPALM on JUNOS
  hosts: junos
  gather_facts: no
  connection: local
  vars:
    ansible_python_interpreter: "/usr/bin/env python"
  tasks:
    - name: Test Napalm on Junos 
      napalm_install_config: 
            hostname: junipervm3
            username: rich
            password: ccie10808
            dev_os: junos
            config_file: new_config.conf
            commit_changes: True
            replace_config: False
